config/routes.rb
require 'sidekiq/web'
OptionsIo::Application.routes.draw do
  match '/users/:id/feed', to: 'users#feed'
  root :to => 'users#new'
  resources :users
  resources :jobs, :only => [:show, :update]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_tags
  resources :job_tags
  resources :notifications, :only => [:index,:destroy]

  match 'joblists/add', to: 'job_lists#add'
  match 'joblists/notes', to: 'job_lists#update_notes'
  match '/users/:id/queue', to: 'users#queue', as: 'queue_user'
  match '/auth/:provider/callback', to: 'omniauth_callbacks#all'
  match '/signout', to: 'sessions#destroy'
  match '/search', to: 'jobs#search'
  match '/location', to: 'static_pages#location'
  match '/add_to_queue/:id', to: 'jobs#add_to_queue', :as => 'add_to_queue'
  match '/remove_from_queue/:id', to: 'jobs#remove_from_queue', :as => 'remove_from_queue'
  match '/wizards/skills', to: 'wizards#skills', :as => 'wizard'
  match '/wizards/locations', to: 'wizards#locations', :as => 'wizard_location'
  match '/users/:id/feed', to: 'users#feed', :as => 'user_feed'
  match '/feed', to: 'users#feed_results', :as => 'feed_results'
  match '/get_job', to: 'jobs#get_job', :as => 'job_info'
  match '/search_tags', to: 'tags#search_skills', :as => 'search_tags'
  match '/search_all_tags', to: 'tags#search_all', :as => 'search_all_tags'
  match '/search_locations', to: 'tags#search_locations', :as => 'search_locations'
  match '/remove_from_queue', to: 'job_lists#destroy', :as => 'remove_from_queue'
  match '/user_locations', to: 'users#add_location', :as => 'user_location'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/job.rb
class Job < ActiveRecord::Base
  # include Tire::Model::Search
  # include Tire::Model::Callbacks

  attr_accessible :name, :description, :email, :company, :source_url, :lat, :lng, :city_id
  has_many :job_tags, :dependent => :destroy
  has_many :tags, :through => :job_tags
  has_many :job_lists, :dependent => :destroy
  has_many :lists, :through => :job_lists
  belongs_to :city

  validates_presence_of :name, :description, :source_url
  validates_uniqueness_of :source_url

  # after_create :tag_job, :notify_users
  # TODO get_job_location here. Fix background worker

  def self.search(params)
    tire.search(load: true) do
      query { string params["search"], default_operator: "AND" } if params["search"].present?
      filter :range, created_at: { gte: Time.zone.now - 24.hours }
    end
  end

  def has_coordinates
    return true if !(self.lat.nil? || self.lng.nil?)
    false
  end

  def has_city?
    return true if self.city != nil
    false
  end

  private 

  def tag_job
    TagWorker.perform_in(10.seconds, self.id)
  end

  def notify_users
    NotificationWorker.perform_in(30.seconds, self.id)
  end

  # def get_job_location
  #   LocationWorker.perform_in(10.seconds, self.id)
  # end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user

  #TODO think about adding this to the lists controller

  def add_to_queue
    @list = current_user.list
    if @list.add_job(params[:id])
      respond_to do |format|
        format.json { render :json => @list.jobs }
      end
    else
      flash[:errors] = "Sorry, something went wrong"
      redirect_to :back
    end
  end

  def remove_from_queue
    list = current_user.list
    list.remove!(params[:id])
    render :json => list
  end

  def update
    list_id = current_user.list.id
    job = JobList.find_by_list_id_and_job_id(list_id, params[:id])
    status = Status.create(status: params[:status], date: Date.today.to_s.slice(5..9).gsub(/-/,'/'), job_list_id: job.id)
    job.status = params[:status]
    job.save
    render :text => "#{status.date}- #{status.status}"
  end

  def get_job
    render :json => Job.find(params[:job_id])
  end

  def search
    if params["search"] == "The Brown Team"
      redirect_to 'http://starlogs.net/nas887/jobhopper'
    else
      @results = Job.search(params)
      render :'search/results'
    end
  end

  def results
  end

  def show
    @job = Job.find(params[:id])
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_result.html.haml
-jobs.each do |job|
  %li
    .job-info
      %h1= job.name
    .buttons
      %button Not Relevant
      -if current_user.list.jobs.include?(job) == false
        =link_to "+ Queue", add_to_queue_path(job), class: "button add_to_queue" 
      %button More info
    %ul.more-info{:style => "display:none;"}
      %li= job.company
      %li= job.source_url
      %li
        %p= job.description

app/views/jobs/show.html.haml
=javascript_include_tag "jobs"
:css
  #queue_buttons:hover {
    cursor: pointer;
  }

.job_show

  .title
    %h1.job_title{style: "display: inline"}= @job.name
    -if current_user.jobs.include?(@job)
      %i.icon-ban-circle{id: "queue_buttons", style: "margin-left: 20px; font-size: 37px; color: rgb(90, 90, 90);"}
    -else
      %i.icon-plus{id: "queue_buttons", style: "margin-left: 20px; font-size: 37px; color: rgb(90, 90, 90);"}
 
  .job-description
    %button{:class => 'remove_from_queue', :id => @job.id, style: "visibility: hidden; position: absolute;"}
    %h4.company_name= @job.company
    %p.description= @job.description
    %br
    %p Apply here:
    %a{:href => @job.source_url, :target => :_blank }=@job.source_url[0..30]


%div{:id => "queue_stuff", :style => "display:none"}
  %i.icon-plus{id: "queue_buttons", style: "margin-left: 20px; font-size: 37px; color: rgb(90, 90, 90);"}
  %i.icon-ban-circle{id: "queue_buttons", style: "margin-left: 20px; font-size: 37px; color: rgb(90, 90, 90);"}