config/routes.rb
require 'sidekiq/web'
OptionsIo::Application.routes.draw do
  match '/users/:id/feed', to: 'users#feed'
  root :to => 'users#new'
  resources :users
  resources :jobs, :only => [:show, :update]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_tags
  resources :job_tags
  resources :notifications, :only => [:index,:destroy]

  match 'joblists/add', to: 'job_lists#add'
  match 'joblists/notes', to: 'job_lists#update_notes'
  match '/users/:id/queue', to: 'users#queue', as: 'queue_user'
  match '/auth/:provider/callback', to: 'omniauth_callbacks#all'
  match '/signout', to: 'sessions#destroy'
  match '/search', to: 'jobs#search'
  match '/location', to: 'static_pages#location'
  match '/add_to_queue/:id', to: 'jobs#add_to_queue', :as => 'add_to_queue'
  match '/remove_from_queue/:id', to: 'jobs#remove_from_queue', :as => 'remove_from_queue'
  match '/wizards/skills', to: 'wizards#skills', :as => 'wizard'
  match '/wizards/locations', to: 'wizards#locations', :as => 'wizard_location'
  match '/users/:id/feed', to: 'users#feed', :as => 'user_feed'
  match '/feed', to: 'users#feed_results', :as => 'feed_results'
  match '/get_job', to: 'jobs#get_job', :as => 'job_info'
  match '/search_tags', to: 'tags#search_skills', :as => 'search_tags'
  match '/search_all_tags', to: 'tags#search_all', :as => 'search_all_tags'
  match '/search_locations', to: 'tags#search_locations', :as => 'search_locations'
  match '/remove_from_queue', to: 'job_lists#destroy', :as => 'remove_from_queue'
  match '/user_locations', to: 'users#add_location', :as => 'user_location'
  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  before_filter :authenticate_user

  def skills
    @skills = current_user.skills
    # @tags = Tag.all.select { |tag| !tag.is_location? }
  end

  def locations
    cookies[:skills] = false
    cookies[:new_user] = false
    @user = current_user
    @locations = Tag.all.select { |tag| tag.is_location? }
    @user_locs = current_user.locations
  end
end

app/helpers/wizards_helper.rb
module WizardsHelper
end

app/views/wizards/_search.html.haml
.new_skills
  %h3 
    =header_1
  =form_tag search_tags_path, :class => "user_tags", :method => "get" do
    =text_field_tag :search, params[:search], :placeholder => "Search", :class => "wizard-search", :autocomplete => 'false'
  %a{href: "#{back}"}
    %button{:class => "next large expand"}
      = feed
    %ul.tag_results
.skills
  %h3=header_2
  %ul.skills-list
    -skills.each do |skill|
      %li
        %a.delete{:id => skill.id, :href => '#'} 
          %button=skill.name 

app/views/wizards/locations.html.haml
=javascript_include_tag "wizards"
=javascript_include_tag "locations"
.wizard_container
  .new_skills
    %h3 Pick locations you're interested in
    = form_tag search_locations_path, :class => "user_tags", :method => "get" do
      = text_field_tag :search, params[:search], :placeholder => "Search for Locations", :class => "wizard-search"
    %a{href: '/'}
      %button{:class => "large expand"} Finished
    %ul.tag_results
  .skills
    %h3 Current Locations
    %ul.skills-list
      -@user_locs.each do |loc|
        %li
          %button=loc.name

app/views/wizards/skills.html.haml
=javascript_include_tag "wizards"
=javascript_include_tag "skills"
.wizard_container
  =render :partial => 'wizards/search', :locals => {:skills => current_user.skills, header_1: "Search Skills", header_2: "Current Skills", back: '/wizards/locations', feed: 'Next'  }