config/routes.rb
require 'sidekiq/web'
OptionsIo::Application.routes.draw do
  match '/users/:id/feed', to: 'users#feed'
  root :to => 'users#new'
  resources :users
  resources :jobs, :only => [:show, :update]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_tags
  resources :job_tags
  resources :notifications, :only => [:index,:destroy]

  match 'joblists/add', to: 'job_lists#add'
  match 'joblists/notes', to: 'job_lists#update_notes'
  match '/users/:id/queue', to: 'users#queue', as: 'queue_user'
  match '/auth/:provider/callback', to: 'omniauth_callbacks#all'
  match '/signout', to: 'sessions#destroy'
  match '/search', to: 'jobs#search'
  match '/location', to: 'static_pages#location'
  match '/add_to_queue/:id', to: 'jobs#add_to_queue', :as => 'add_to_queue'
  match '/remove_from_queue/:id', to: 'jobs#remove_from_queue', :as => 'remove_from_queue'
  match '/wizards/skills', to: 'wizards#skills', :as => 'wizard'
  match '/wizards/locations', to: 'wizards#locations', :as => 'wizard_location'
  match '/users/:id/feed', to: 'users#feed', :as => 'user_feed'
  match '/feed', to: 'users#feed_results', :as => 'feed_results'
  match '/get_job', to: 'jobs#get_job', :as => 'job_info'
  match '/search_tags', to: 'tags#search_skills', :as => 'search_tags'
  match '/search_all_tags', to: 'tags#search_all', :as => 'search_all_tags'
  match '/search_locations', to: 'tags#search_locations', :as => 'search_locations'
  match '/remove_from_queue', to: 'job_lists#destroy', :as => 'remove_from_queue'
  match '/user_locations', to: 'users#add_location', :as => 'user_location'
  mount Sidekiq::Web => '/sidekiq'

end

app/views/layouts/_location.html.haml
<script type="text/javascript">
    var x=document.getElementById("demo");
    function getLocation()
    {
    if (navigator.geolocation)
      {
        console.log('fuck');
      navigator.geolocation.getCurrentPosition(showPosition);
      }
    else{x.innerHTML="Geolocation is not supported by this browser.";}
    }
  function showPosition(position)
    {
    x.innerHTML="Latitude: " + position.coords.latitude + 
    "<br>Longitude: " + position.coords.longitude; 
    }
</script>

app/views/layouts/_navigation.html.haml
.white_space
  %p stuff to take up the white space
.nav
  -if current_user
    = link_to "Sign Out", signout_path, :class => "btn btn-large btn-danger"
  -else
    = link_to "Sign In", new_session_path, :class => "btn btn-large btn-inverse"
    = link_to "Sign Up", new_user_path, :class => "btn btn-large btn-primary"

app/views/layouts/application.html.haml
%html
  %head
    %title JobHopper
    = stylesheet_link_tag "application"
    = stylesheet_link_tag "custom"
    = javascript_include_tag "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"
    = csrf_meta_tags
    %link{href: 'http://fonts.googleapis.com/css?family=Lato', rel:'stylesheet', type:'text/css'}
    %link{href: "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css", rel:"stylesheet"}
    %link{href: 'http://fonts.googleapis.com/css?family=Montserrat+Subrayada', rel:'stylesheet', type:'text/css'}
  %body
    #wrapper
      =render 'shared/header'
      .container
        :javascript
          if (navigator.geolocation)
          {
            navigator.geolocation.getCurrentPosition(sendPositionToServer);
          }
          else
          {
            x.innerHTML="Geolocation is not supported by this browser.";
          }
          function sendPositionToServer(position)
          {
            $.ajax({
              method: 'post',
              url: '/user_locations',
              data: { "lat":"" + position.coords.latitude + "", "lng": "" + position.coords.longitude + "" }
            })
          }
        .notifications
          =render :partial => 'notifications/dropdown', locals: {user: current_user }
        =render :partial => 'static_pages/queue', locals: {user: current_user}
        =render 'shared/alerts'
        = yield
      = render 'shared/footer'

app/views/layouts/test.html.erb
<head>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag "custom" %>
  <link href='http://fonts.googleapis.com/css?family=Average' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat+Subrayada' rel='stylesheet' type='text/css'>
  <title>JobHopper</title>
</head>
<body>
  <%= yield %>
</body>